### ISSUE TITLE
Support for additional panic functions

### ISSUE THREAD

**Issue by ryan-summers** [jamesmunns/panic-preserve#2]
In some applications, it may be desirable to perform other actions in the panic handler (e.g. powering down devices, shutting off interfaces, clearing displays, etc.) which would be defined in a user-provided panic handler.

Right now, it's not possible to inject custom behavior into a panic handler and use `panic_persist` at the same time.

Possible solutions:
* Make the default `panic-handler` in `panic_persist` opt-out
* Provide a public API from `panic_persist` for the user to manually write into the panic dump memory without a panic handler being present

Sample:
Cargo.toml
```rust
panic_handler = { default-features = false }
```

panic.rs
```rust
#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {
    cortex_m::interrupt::disable();
    panic_persist::write_panic_info(&info);
    shutdown_devices();
    cortex_m::periupheral::SCB::sys_reset();
}
```

**Comment by ryan-summers** [comment]
Ah, after posting this, I now see the change is in `master`, but not on `crates.io`. Any change we could release the updated version?

**Comment by jamesmunns** [comment]
Released! Sorry for the silly delay. This is now in v0.3.0.
