### ISSUE TITLE
No message persisted on Ambiq Apollo3

### ISSUE THREAD

**Issue by gauteh** [jamesmunns/panic-preserve#6]
Hi,

I am trying to use this crate on an ambiq apollo3, but I always get None back. I've set up memory.x as follows:

```
ENTRY(Reset_Handler)
MEMORY
{
  FLASH (rx) : ORIGIN = 0x00010000, LENGTH = (0x000F0000 - (0x00010000))
  RAM_NVIC (rwx) : ORIGIN = 0x10000000, LENGTH = 0x100
  RAM (rwx) : ORIGIN = (0x10000000 + 0x100), LENGTH = (384K - (0x100) - 1K)
  PANDUMP: ORIGIN = (0x10000000 + 384K - 1K), LENGTH = 1K
}

_panic_dump_start = ORIGIN(PANDUMP);
_panic_dump_end   = ORIGIN(PANDUMP) + LENGTH(PANDUMP);

```

and do:

```
panic_persist::get_panic_message_persist()
```

at startup, and some `panic!("asdf")` further down my program.

Is there any chance that there is a bootloader that wipes RAM on reset? There are some `wipe_sram` functions in the bootloader, but I couldn't really figure out if it is called every time or just when a new program is loaded.

**Comment by jamesmunns** [comment]
Yeah, I'm not sure :(. It's possible the bootloader is clearing SRAM on boot/swreset, I'm not familiar with the ambiq apollo3.

If you can figure out a way to retain some region/disable the hw clearing (not sure what other impacts that would have), and can save ANY value after reboot, you could likely get panic-persist working.

**Comment by gauteh** [comment]
Thanks. I did eventually find some functions named wipe_sram in the bootloader, didn't investigate fully but I assume they are the culprit. Eventually figured out how to persist panics to a modem hooked over i2c through some considerably unsafe'ty (so now I get panics transmitted over cellular!). That'll have to do for now!
